const library = module.exports = {}
// ===============================   运营活动
// 活动管理
library.activity = [
  { name: '活动名称',
    width: 200,
    dataIndex: 'name' },
  { name: '状态',
    width: 114,
    dataIndex: 'status' },
  { name: '上线时间',
    width: 200,
    dataIndex: 'startTime' },
  { name: '下线时间',
    width: 200,
    dataIndex: 'endTime' },
  { name: '申请人',
    width: 100,
    dataIndex: 'creatName' },
  { name: '测试人',
    width: 100,
    dataIndex: 'testName' },
  { name: '操作',
    width: 200,
    dataIndex: 'operate' },
];

//活动配置
library.activityConfig = [
  { name: '活动名称',
    width: 160,
    dataIndex: 'name' },
  { name: '资源位',
    width: 174,
    dataIndex: 'resources' },
  { name: '上线时间',
    width: 200,
    dataIndex: 'startTime' },
  { name: '下线时间',
    width: 200,
    dataIndex: 'endTime' },
  { name: '申请人',
    width: 100,
    dataIndex: 'creatName' },
  { name: '审核人',
    width: 100,
    dataIndex: 'testName' },
  { name: '审核状态',
    width: 114,
    dataIndex: 'status' },
  { name: '操作',
    width: 180,
    dataIndex: 'operate' },
];

// 活动冲突
library.activityTable = [
  { name: '活动名称',
    dataIndex: 'name' },
  { name: '上线时间',
    dataIndex: 'startTime' },
  { name: '下线时间',
    dataIndex: 'endTime' },
  { name: '申请人',
    dataIndex: 'apply' },
];
// 运营策略
library.operation = [
  { name: '活动名称',
    width: 200,
    dataIndex: 'name' },
  { name: '状态',
    width: 114,
    dataIndex: 'status' },
  { name: '上线时间',
    width: 200,
    dataIndex: 'startTime' },
  { name: '下线时间',
    width: 200,
    dataIndex: 'endTime' },
  { name: '申请人',
    width: 100,
    dataIndex: 'creatorName' },
  { name: '测试人',
    width: 100,
    dataIndex: 'testerName' },
  { name: '操作',
    width: 285,
    dataIndex: 'operate' },
];
// 策略冲突
library.operationTable = [
  { name: '活动名称',
    dataIndex: 'name' },
  { name: '上线时间',
    dataIndex: 'startTime' },
  { name: '下线时间',
    dataIndex: 'endTime' },
  { name: '申请人',
    dataIndex: 'apply' },
];

// 常用工具
library.tools = [
  { name: '活动名称',
    width: 200,
    dataIndex: 'name' },
  { name: '类型',
    width: 148,
    dataIndex: 'type' },
  {
    name: '价格',
    width: 148,
    dataIndex: 'currentPrice'
  },
  { name: '状态',
    width: 114,
    dataIndex: 'status' },
  { name: '上线时间',
    width: 200,
    dataIndex: 'startTime' },
  { name: '申请人',
    width: 100,
    dataIndex: 'creatName' },
  { name: '测试人',
    width: 100,
    dataIndex: 'testName' },
  { name: '操作',
    width: 285,
    dataIndex: 'operate' },
];
// 工具冲突
library.toolsTable = [
  { name: '活动名称',
    dataIndex: 'name' },
  { name: '上线时间',
    dataIndex: 'startTime' },
  { name: '申请人',
    dataIndex: 'apply' },
];
// 标识码冲突
library.toolsPrefix = [
  { name: '活动名称',
    dataIndex: 'name' },
  { name: '标识码',
    dataIndex: 'prefix' },
  { name: '上线时间',
    dataIndex: 'startTime' },
  { name: '申请人',
    dataIndex: 'apply' },
];
// 一码多用优惠码数据
library.coupon1vnStatistics = [
  { name: '活动名称',
    dataIndex: 'activityName',
    width: 160,
  },
  { name: '活动状态',
    dataIndex: 'activityStatus',
    width: 90,
  },
  { name: '优惠码',
    dataIndex: 'code',
    width: 110,
  },
  { name: '优惠码领取上限',
    dataIndex: 'limit',
    width: 70,
  },
  { name: '新用户兑换人数',
    dataIndex: 'newUserNum',
    width: 80,
  },
  { name: '老用户兑换人数',
    dataIndex: 'oldUserNum',
    width: 78,
  },
  { name: '实名认证人数',
    dataIndex: 'oauthNum',
    width: 74,
  },
  { name: '交押金人数',
    dataIndex: 'bondNum',
    width: 64,
  },
  { name: '新用户订单量',
    dataIndex: 'newUserOrdeNum',
    width: 64,
  },
  { name: '老用户订单量',
    dataIndex: 'oldUserOrderNum',
    width: 64,
  },
  { name: '操作',
    dataIndex: 'operate',
    width: 90,
  },
];
// 一码单用优惠码数据
library.coupon1v1Statistics = [
  { name: '活动名称',
    dataIndex: 'activityName',
    width: 160,
  },
  { name: '活动状态',
    dataIndex: 'activityStatus',
    width: 90,
  },
  { name: '优惠码个数',
    dataIndex: 'couponNum',
    width: 80,
  },
  { name: '新用户兑换人数',
    dataIndex: 'newUserNum',
    width: 68,
  },
  { name: '老用户兑换人数',
    dataIndex: 'oldUserNum',
    width: 68,
  },
  { name: '实名认证人数',
    dataIndex: 'oauthNum',
    width: 68,
  },
  { name: '交押金人数',
    dataIndex: 'bondNum',
    width: 64,
  },
  { name: '新用户订单量',
    dataIndex: 'newUserOrdeNum',
    width: 64,
  },
  { name: '老用户订单量',
    dataIndex: 'oldUserOrderNum',
    width: 64,
  },
  { name: '操作',
    dataIndex: 'operate',
    width: 90,
  },
];
// 领用车券数据
library.couponRedPacketPageLinkStatistics = [
  { name: '活动名称',
    dataIndex: 'activityName',
    width: 150,
  },
  { name: '活动状态',
    dataIndex: 'activityStatus',
    width: 75,
  },
  { name: '页面PV',
    dataIndex: 'pv',
    width: 70,
  },
  { name: '页面UV',
    dataIndex: 'uv',
    width: 70,
  },
  { name: '注册手机号人数',
    dataIndex: 'newUserNum',
    width: 77,
  },
  { name: '交押金人数',
    dataIndex: 'bondNum',
    width: 77,
  },
  { name: '实名认证人数',
    dataIndex: 'oauthNum',
    width: 89,
  },
  { name: '新用户订单量',
    dataIndex: 'newUserOrdeNum',
    width: 89,
  },
  { name: '老用户订单量',
    dataIndex: 'oldUserOrderNum',
    width: 89,
  },
  { name: '操作',
    dataIndex: 'operate',
    width: 90,
  },
];
// 线上活动数据
library.activityStatistics = [
  { name: '活动名称',
    dataIndex: 'activityName',
  },
  { name: 'time',
    dataIndex: 'time',
  },
  { name: '资源位',
    dataIndex: 'resource',
  },
  { name: 'PV',
    dataIndex: 'pv',
  },
  { name: 'UV',
    dataIndex: 'uv',
  },
  { name: '点击量',
    dataIndex: 'click',
  },
  { name: '操作',
    dataIndex: 'operate',
  },
];
// 二维码管理
library.qrcode = [
  { name: '批次',
    width: 200,
    dataIndex: 'batch' },
  { name: '创建人',
    width: 160,
    dataIndex: 'creatName' },
  { name: '时间',
    width: 200,
    dataIndex: 'time' },
  { name: '数量',
    width: 100,
    dataIndex: 'num' },
  { name: '统计',
    width: 100,
    dataIndex: 'statistics' },
  { name: '操作',
    width: 260,
    dataIndex: 'operate' },
];
// 二维码下载
library.qrcodeStatistics = [
  { name: '序号',
    dataIndex: 'statisticsIdx' },
  { name: '扫描数',
    dataIndex: 'scanNum' },
  { name: '注册数',
    dataIndex: 'registerNum' },
  { name: '用车数',
    dataIndex: 'carNum' },
];

// ===============================   围栏管理
// 围栏订单
library.fenceOrder = [
  { name: '排名',
    width: 100,
    dataIndex: 'rank' },
  { name: '区域',
    dataIndex: 'area' },
  { name: '订单量',
    dataIndex: 'order' },
  { name: '解锁车辆数',
    dataIndex: 'value' },
  // { name: '单车效率(订单/车)',
  //   width: 160,
  //   dataIndex: 'rate' },
  { name: '报修率(%)',
    dataIndex: 'repairRate' },
  { name: 'B类报修(%)',
    dataIndex: 'repairSecondRate' },
//   { name: '车辆流入(辆)',
//     width: 120,
//     dataIndex: 'inNum' },
//   { name: '车辆流出（辆）',
//     width: 120,
//     dataIndex: 'outNum' },
//   { name: '围栏内首单用户数',
//     width: 120,
//     dataIndex: 'firstOrderNum' },
];

// ===============================   探索性需求
// 车牌号信息
library.licensePlateNum = [
  { name: '车牌号',
    width: 80,
    dataIndex: 'bikeNo' },
  { name: '订单号',
    width: 90,
    dataIndex: 'orderId' },
  { name: '姓名',
    width: 80,
    dataIndex: 'name' },
  { name: '手机号',
    width: 120,
    dataIndex: 'mobile' },
  { name: '人群',
    width: 80,
    dataIndex: 'person' },
  { name: '城市',
    width: 80,
    dataIndex: 'origin' },
  { name: '开始时间',
    width: 170,
    dataIndex: 'startTime' },
  { name: '结束时间',
    width: 170,
    dataIndex: 'endTime' },
  { name: '操作',
    width: 170,
    dataIndex: 'operate' },
];

// ===============================   客服管理
// 余额余额管理
library.balanceMag = [
  { name: '操作',
    width: 135,
    dataIndex: 'operate' },
  { name: '用户ID',
    width: 65,
    dataIndex: 'userId' },
  { name: '手机号',
    width: 100,
    dataIndex: 'phone' },
  { name: '充值金额',
    width: 65,
    dataIndex: 'money' },
  { name: '状态',
    width: 65,
    dataIndex: 'status' },
  { name: '交易单号',
    width: 90,
    dataIndex: 'orderId' },
  { name: '描述',
    width: 70,
    dataIndex: 'detail' },
  { name: '充值项',
    width: 65,
    dataIndex: 'orderName' },
  { name: '充值时间',
    width: 88,
    dataIndex: 'startTime' },
  { name: '完成时间',
    width: 88,
    dataIndex: 'endTime' },
  { name: '交易渠道',
    width: 65,
    dataIndex: 'type' },
  { name: '终端',
    width: 60,
    dataIndex: 'terminal' },
];
// 余额押金管理
library.depositMag = [
  { name: '操作',
    width: 135,
    dataIndex: 'operate' },
  { name: '用户ID',
    width: 60,
    dataIndex: 'userId' },
  { name: '手机号',
    width: 100,
    dataIndex: 'phone' },
  { name: '充值金额',
    width: 64,
    dataIndex: 'money' },
  { name: '状态',
    width: 80,
    dataIndex: 'status' },
  { name: '描述',
    width: 100,
    dataIndex: 'detail' },
  { name: '充值时间',
    width: 140,
    dataIndex: 'startTime' },
  { name: '完成时间',
    width: 140,
    dataIndex: 'endTime' },
  { name: '支付渠道',
    width: 64,
    dataIndex: 'type' },
  { name: '终端',
    width: 60,
    dataIndex: 'terminal' },
];
// 余额押金订单详情管理
library.orderDetail = [
  { name: '实付金额',
    width: 65,
    dataIndex: 'payMoney' },
  { name: '订单状态',
    width: 140,
    dataIndex: 'status' },
  { name: '车牌号',
    width: 80,
    dataIndex: 'carNum' },
  { name: '订单创建时间',
    width: 139,
    dataIndex: 'startTime' },
  { name: '订单结束时间',
    width: 139,
    dataIndex: 'endTime' },
  { name: '起始区域',
    width: 65,
    dataIndex: 'origin' },
  { name: '结束区域',
    width: 65,
    dataIndex: 'destination' },
  { name: '订单总路程(m)',
    width: 70,
    dataIndex: 'path' },
  { name: '订单总时间(s)',
    width: 70,
    dataIndex: 'time' },
  { name: '红包类型',
    width: 77,
    dataIndex: 'type' },
  { name: '红包折扣',
    width: 66,
    dataIndex: 'discount' },
  { name: '产生红包个数',
    width: 90,
    dataIndex: 'redNum' },
  { name: '剩余红包个数',
    width: 91,
    dataIndex: 'surplus' },
  // { name: '操作',
  //   dataIndex: 'operate' },
];

library.orderNumberInfo = [
  {
    name:'用户ID',
    width:60,
    dataIndex:'id'
  },
  {
    name:'手机号',
    width:80,
    dataIndex:'tel'
  },
  {
    name:'真实姓名',
    width:50,
    dataIndex:'realname'
  },
  {
    name:'余额',
    width:40,
    dataIndex:'balance'
  },
  {
    name:'活动余额',
    width:40,
    dataIndex:'fbalance'
  },
  {
    name:'认证',
    width:60,
    dataIndex:'oauth'
  },
  {
    name:'用户类别',
    width:80,
    dataIndex:'cls'
  },
  {
    name:'第三方用户标识',
    width:80,
    dataIndex:'third_user_id'
  },
  {
    name:'押金',
    width:40,
    dataIndex:'bond'
  },
  {
    name:'订单信息',
    width:60,
    dataIndex:'trade_info'
  },
]
// 操作记录
library.record = [
  { name: '序号',
    width: 45,
    dataIndex: 'idx' },
  { name: '客服平台',
    width: 60,
    dataIndex: 'servicer' },
  { name: '时间',
    width: 150,
    dataIndex: 'time' },
  { name: '用户手机号',
    width: 100,
    dataIndex: 'userPhone' },
  { name: '用户交易单号',
    width: 220,
    dataIndex: 'order' },
  { name: '操作内容',
    width: 100,
    dataIndex: 'operate' },
  { name: '金额',
    width: 52,
    dataIndex: 'money' },
  { name: '来源渠道',
    width: 65,
    dataIndex: 'origin' },
  { name: '到账渠道',
    width: 65,
    dataIndex: 'destination' },
  { name: '备注',
    width: 80,
    dataIndex: 'content' },
];
//认证审核驳回原因
library.rejectCheckReason = [
  '图片非学生证',
  '图片为学生证反面',
  '学生证为临时卡',
  '学生证重要信息模糊',
  '学生证重要信息缺失',
  '新生未提供录取通知书照片',
  '学生证信息与填写的信息不符',
  '录取通知书没有学号，需提供身份证',
  '身份不符合要求',
];

// ===============================   国际数据
library.internationalOrderColumns = [
  { name: '车牌号',
    width: 80,
    dataIndex: 'bikeNo' },
  { name: '订单号',
    width: 90,
    dataIndex: 'orderId' },
  { name: '姓名',
    width: 80,
    dataIndex: 'name' },
  { name: '手机号',
    width: 120,
    dataIndex: 'mobile' },
  { name: '设备',
    width: 80,
    dataIndex: 'device' },
  { name: '国别',
    width: 80,
    dataIndex: 'person' },
  { name: '开始时间',
    width: 170,
    dataIndex: 'startTime' },
  { name: '结束时间',
    width: 170,
    dataIndex: 'endTime' },
];
//区域订单统计
library.areaOrderStatistics = [
  {
    name:'区域围栏',
    width:'10%',
    dataIndex:'name',
  },
  {
    name:'围栏订单量',
    width:'10%',
    dataIndex:'count',
  },
  {
    name:'操作',
    width:'10%',
    dataIndex:'operate',
  }
];
//区域订单列表
library.areaOrderList = [
  {
    name:'单号',
    width: 'auto',
    dataIndex: 'order',
  },
  {
    name:'车牌号',
    width:'auto',
    dataIndex:'carno',
  },
  {
    name:'用户ID',
    width: 'auto',
    dataIndex: 'userid',
  },
  {
    name:'用户名',
    width:'auto',
    dataIndex:'username',
  },
  {
    name:'电话',
    width:'auto',
    dataIndex:'tel'
  },
  {
    name:'操作',
    width:'auto',
    dataIndex:'operate',
  }
];

// ===============================   Kefu 后台
library.cityList = [
  { name: '省份',
    width: '15%',
    dataIndex: 'province' },
  { name: '城市',
    width: '25%',
    dataIndex: 'city' },
  { name: '区域',
    width: '15%',
    dataIndex: 'region' },
  { name: '城市code',
    width: '15%',
    dataIndex: 'cityCode' },
  { name: '当前模式',
    width: '10%',
    dataIndex: 'modal' },
  { name: '是否开城',
    width: '20%',
    dataIndex: 'show' },
];
// 众包找车
library.findBike = [
  { title: '城市',
    width: '9%',
    key: 'city_name' },
  { title: '非活跃时长',
    width: '9%',
    key: 'silence_time' },
  { title: '区域选择',
    width: '9%',
    key: 'rail_ids' },
  { title: '普通用户奖励',
    width: '9%',
    key: 'user_rewards' },
  { title: '众包用户奖励',
    width: '11%',
    key: 'collector_rewards' },
  { title: '阶梯奖励',
    width: '9%',
    key: 'collector_step_rewards' },
  { title: '操作人',
    width: '9%',
    key: 'create_name' },
  { title: '状态',
    width: '9%',
    key: 'statusText' },
  { title: '操作',
    width: '26%',
    key: 'operation' },
];
