
import moment from 'moment';
export const activity_initial_data = {
    startTime: moment().format('YYYY-MM-DD HH:mm:ss'),
    endTime: moment().add(1, 'days').format('YYYY-MM-DD HH:mm:ss'),
    oauth: '1,5',
    userType: '1,2',
    activityName: '',
    value: ['all'],
    total: '',
    limit: '',
    getNum: '',
    count: '',
    discount: '',
    limitDay: '',
    radio: 2,
    typeRadio: 0,
    prefix: '',
    flag: '',
    exchangeType: 0,
    amount: '',
    isPay: 0,
    // 老用户领取
    getNumOld: '',
    countOld: '',
    discountOld: '',
    limitDayOld: '',
    radioOld: 2,
    typeRadioOld: 0,
    // exchangeTypeOld: 0,
    amountOld: '',
    isPayOld: 0,
    isPayNumOld: '20',
    isPayNum: '20',
}